// demo/Counter.jsx
import { useState } from 'react'
import { Button, Tag, message } from 'antd'
import styled from 'styled-components'

const Wrapper = styled.div`
  max-width: 420px;
  margin: 40px auto;
  padding: 24px;
  border: 1px solid #f0f0f0;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
`

const Header = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
`

const Title = styled.span`
  font-size: 16px;
  font-weight: 600;
`

const Display = styled.div`
  text-align: center;
  font-size: 28px;
  font-weight: 600;
  margin: 24px 0;
`

const Actions = styled.div`
  display: flex;
  justify-content: center;
  gap: 8px;
  flex-wrap: wrap;
`

export default function Counter() {
  const [count, setCount] = useState(0)

  return (
    <Wrapper>
      <Header>
        <Title>Ant Design Counter</Title>
        <Tag color="success">React Transfer Demo</Tag>
      </Header>
      <Display>Count: {count}</Display>
      <Actions>
        <Button type="primary" onClick={() => setCount(c => c + 1)}>+1</Button>
        <Button onClick={() => setCount(c => c - 1)}>-1</Button>
        <Button onClick={() => { setCount(0); message.info('Count 已重置') }}>Reset</Button>
      </Actions>
    </Wrapper>
  )
}

// demo/Counter.vue
<template>
  <el-card class="counter-card" shadow="hover">
    <template #header>
      <div class="card-header">
        <span>Element Plus Counter</span>
        <el-tag type="success">Vue Transfer Demo</el-tag>
      </div>
    </template>

    <div class="count-display">
      <el-text size="large" type="primary">Count: {{ count }}</el-text>
    </div>

    <div class="actions">
      <el-button type="primary" @click="increment">+1</el-button>
      <el-button type="warning" @click="decrement">-1</el-button>
      <el-button type="info" @click="reset">Reset</el-button>
    </div>
  </el-card>
</template>

<script setup>
import { ElCard, ElTag, ElText, ElButton, ElMessage } from 'element-plus'
import { ref } from 'vue'

const count = ref(0)

function increment() {
  count.value++
}

function decrement() {
  count.value--
}

function reset() {
  count.value = 0
  ElMessage.info('Count 已重置')
}
</script>

<style scoped>
.counter-card {
  max-width: 420px;
  margin: 40px auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.count-display {
  text-align: center;
  font-size: 28px;
  font-weight: 600;
  margin: 24px 0;
}

.actions {
  display: flex;
  justify-content: center;
  gap: 12px;
  flex-wrap: wrap;
}
</style>
